### ISSUE TITLE
Breaks Android and iOS, but runs in a browser

### ISSUE THREAD

**Issue by salamanders** [ecwyne/meteor-polymer-elements#10]
This plugin works in the browser, but when I try to run it in an android or iOS emulator, no luck.  I think it is trying to download all of the files for all of the components?

```
meteor create oneshot
cd oneshot

mkdir server
meteor remove insecure autopublish
meteor add accounts-ui accounts-google
meteor add ecwyne:polymer-elements
meteor run # Throws in all the polymer files
meteor install-sdk android
meteor add-platform android 
meteor run android

**Comment by salamanders** [comment]
I'm a bit suspicious - not installing the content into /public means *everything* will be parsed and sent to the front end through meteor.  Which is redundant with polymer's method, yes?

**Comment by ecwyne** [comment]
These issues are likely mitigated with the newest release of the package.

@salamanders can you confirm this?

**Comment by salamanders** [comment]
I'm getting in the Android emulator:
Page loads.  Polymer content doesn't.
chrome://inspect shows
Failed to load resource: the server responded with a status of 404 (Not Found) http://meteor.local/bower_components/webcomponentsjs/webcomponents.js

**Comment by ecwyne** [comment]
@salamanders is this related to https://github.com/meteor/meteor/issues/2822 ?

**Comment by salamanders** [comment]
Don't think so.  Not currently building with this in a project, so can't repro.  Will reopen if encountered again.
