### ISSUE TITLE
Need better examples

### ISSUE THREAD

**Issue by vangorra** [ecwyne/meteor-polymer-elements#13]
The example could be clearer on what to expect.
Also, some tips on how to use polymer with meteor would be good too. I for one had a hard time figuring out how to get buttons in a dialog to fire.
I'd be willing to write the examples if you like.

**Comment by ecwyne** [comment]
This sounds like a great use of the wiki on the repo! You can absolutely feel free to contribute to the wiki and I'll link from the README to the appropriate wiki pages! I'd love if the wiki because a source of info for using polymer with meteor.

**Comment by vangorra** [comment]
Added a page that should help avoid some confusion.

**Comment by ecwyne** [comment]
@vangorra Those look fantastic! Thanks so much for contributing!!
