### ISSUE TITLE
Uncaught TypeError: Cannot read property 'resolveDom' of undefined 

### ISSUE THREAD

**Issue by aon108** [ecwyne/meteor-polymer-elements#14]
Thanks for putting together this package.

I cannot get it to work by following the instructions outlined in readme files. I added both packages and use  {{> paper_checkbox_link}}. I get the above error in console.

Additionally this error:
 You tried to use polymer without loading it first. To load polymer, <link rel="import" href="components/polymer/polymer.html"> 

Very much appreciate your help

**Comment by ecwyne** [comment]
can you provide the steps to reproduce this error as well as what browser you're using. You shouldn't need to add `ecwyne:polymer` because Polymer is added for  you automatically.

**Comment by aon108** [comment]
Thank you very much for your quick response. This issue has now been fixed by removing ecwyne:polymer package. Thank you for your support!
