### ISSUE TITLE
Polymer not updating.

### ISSUE THREAD

**Issue by vangorra** [ecwyne/meteor-polymer-elements#17]
Running meteor update and starting meteor does not update the polymer library. How is this achieved? I'm still running 0.5.0.

**Comment by ecwyne** [comment]
Ah, I see. 

You likely still have Polymer 0.5.0 saved in your `Public` folder. Delete the entire directory from the `Public` directory and you should be good to go.

(The newest updates to the package doesn't install Polymer in that way)

**Comment by vangorra** [comment]
Previously, I thought deleting the public folder would force the files to be updated. I've tried it and started meteor. No new files are downloaded.

**Comment by ecwyne** [comment]
That's correct. The new version of the package (1.0.6 and up) no longer download the files to the public directory.

**Comment by vangorra** [comment]
That makes sense. I'll try it out.
