### ISSUE TITLE
using this with spiderable and facebook-sdk it breaks reading of opengraph tags by Facebook scraper

### ISSUE THREAD

**Issue by milanzigmond** [ecwyne/meteor-polymer-elements#18]
testing project is here: https://github.com/milanzigmond/polymer-fbsdk

list of packages used: http://prntscr.com/6r4357

this example online looks like this: milanzigmond.com (if you click on click me button it shows FB share dialog with some error text - this is there due to errors from polymer) 

to see what spiderable sees look at: http://milanzigmond.com/?_escaped_fragment_= (you will see all the errors)

if your package is not installed, all works fine and spiderable don't have any errors to show and shows correct sharing meta data

can u have a look into it please
thanks
milan

**Comment by milanzigmond** [comment]
ok I fixed the errors by including bower_components in public folder, but Facebook scraper now thinks that opengraph meta tags are in the body, so I guess you are editing head somehow which breaks existing metatags, i'll look into it more and write if I find something

**Comment by milanzigmond** [comment]
this problem is related to phantomjs, it thows error, when i try to include script webcomponents.min.js:
ReferenceError: Can't find variable: Window http://milanzigmond.com/bower_components/webcomponentsjs/webcomponents.min.js:11 http://milanzigmond.com/bower_components/webcomponentsjs/webcomponents.min.js:11

**Comment by ecwyne** [comment]
https://github.com/webcomponents/webcomponentsjs/issues/239
