### ISSUE TITLE
how to pass args to attributeObject ?

### ISSUE THREAD

**Issue by ramstein74** [ecwyne/meteor-polymer-elements#20]
in this example 
{{> paper_checkbox attrs=attributeObject}}

what if i use this inside an each statment ?
for each i want to pass a value to attibuteObject like 
each param
{{> paper_checkbox attrs=attributeObject(param)}}
/each
how do i do it ?

thank you

**Comment by ecwyne** [comment]
@ramstein74 there would be two different ways to accomplish this. If you can share your project code I can advise a method to use.

# 1. Use Template Helper
```javascript
  Template.myTemplate.helpers({
    attributeObject: function (){
      //"this" is the data context of your template
      return {checked: this.checked}
   }
  });
```

# 2. Store object in mongo document
```json
  //mongo document
  {
    "name": "My Name",
    "occupation": "My Occupation",
    "attributeObject": {"checked": true}
  }
```

**Comment by ramstein74** [comment]
Ok if that is the way it works.

Just dont understand why you did it like that.
It would be easy to debug if we could write in the html all the params to polymer.

Hiding all inside an object repeatedly for every record i may need,  seems a waste of space( if inside collection)  and harder to debug and code.

**Comment by ecwyne** [comment]
Update: there will be an additional way of creating this attribute object using subexpressions! See the proposal [here](https://meteor.hackpad.com/Handlebars-subexpressions-hxHIYbYlsBr) and the PR [here](https://github.com/meteor/meteor/pull/4101)
