### ISSUE TITLE
No such template: core_toollookup.js:122

### ISSUE THREAD

**Issue by rohanray** [ecwyne/meteor-polymer-elements#21]
Hi,

I wish to use Polymer core tools as well. Please let me know if it's possible. I added     {{> core_tool }}, however I'm getting an error saying "No such template: core_toollookup.js:122" 

Packages being used:

meteor-platform
autopublish
insecure
ecwyne:polymer-elements

Using METEOR@1.1.0.2

Thanks
Rohan

**Comment by ecwyne** [comment]
I'm not sure what you mean by core-tools

You can find all available elements (core/paper) [here](https://github.com/ecwyne/meteor-polymer-elements/tree/master/lib/bower_components)
