### ISSUE TITLE
multiple import of same import

### ISSUE THREAD

**Issue by ramstein74** [ecwyne/meteor-polymer-elements#22]
![image](https://cloud.githubusercontent.com/assets/1210858/7346999/d3c9fcf2-ecdb-11e4-9b94-febb41b2dcb7.png)

hello using your suggestion 

i have this code
           {{#core_item id="core_item" attrs=item }}{{/core_item}}
            {{#core_item id="core_item" attrs=item }}{{/core_item}}

as i see using chrome dev tools, there is an import for each core-item.html
Is this effective as i can have hundreds of core-items ?
How can i have only one import  for the same kind ?

Regards

**Comment by ecwyne** [comment]
https://github.com/ecwyne/meteor-polymer-elements#vanilla_polymerhtml

The helpers are simply there for your convenience.

**Comment by ramstein74** [comment]
ok i understand. thank you
