### ISSUE TITLE
installing polymer-elements

### ISSUE THREAD

**Issue by vhuerta** [ecwyne/meteor-polymer-elements#5]
im getting this error after install this plugin and exec meteor run

I20141111-15:41:42.431(-6)? installing polymer-elements
W20141111-15:41:48.055(-6)? (STDERR)
W20141111-15:41:48.056(-6)? (STDERR) /Users/bcore/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:206
W20141111-15:41:48.056(-6)? (STDERR) 						throw(ex);
W20141111-15:41:48.056(-6)? (STDERR) 						      ^
W20141111-15:41:48.062(-6)? (STDERR) polymer: Unable to find suitable version for polymer
W20141111-15:41:48.062(-6)? (STDERR)     at Object.Future.wait (/Users/bcore/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:326:15)
W20141111-15:41:48.063(-6)? (STDERR)     at Object.install (packages/meteor/helpers.js:118)
W20141111-15:41:48.063(-6)? (STDERR)     at Package (packages/ecwyne:polymer-elements/polymer-elements.js:25)
W20141111-15:41:48.063(-6)? (STDERR)     at /Users/bcore/Desarrollo/js/todos/.meteor/local/build/programs/server/packages/ecwyne_polymer-elements.js:47:4
W20141111-15:41:48.063(-6)? (STDERR)     at /Users/bcore/Desarrollo/js/todos/.meteor/local/build/programs/server/packages/ecwyne_polymer-elements.js:54:3
W20141111-15:41:48.063(-6)? (STDERR)     at /Users/bcore/Desarrollo/js/todos/.meteor/local/build/programs/server/boot.js:168:10
W20141111-15:41:48.063(-6)? (STDERR)     at Array.forEach (native)
W20141111-15:41:48.064(-6)? (STDERR)     at Function._.each._.forEach (/Users/bcore/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141111-15:41:48.064(-6)? (STDERR)     at /Users/bcore/Desarrollo/js/todos/.meteor/local/build/programs/server/boot.js:82:5
W20141111-15:41:48.064(-6)? (STDERR)     - - - - -
W20141111-15:41:48.064(-6)? (STDERR)     at createError (/Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/lib/util/createError.js:4:15)
W20141111-15:41:48.064(-6)? (STDERR)     at Manager._electSuitable (/Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/lib/core/Manager.js:763:15)
W20141111-15:41:48.064(-6)? (STDERR)     at /Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/lib/core/Manager.js:558:25
W20141111-15:41:48.064(-6)? (STDERR)     at _fulfilled (/Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:787:54)
W20141111-15:41:48.064(-6)? (STDERR)     at self.promiseDispatch.done (/Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:816:30)
W20141111-15:41:48.064(-6)? (STDERR)     at Promise.promise.promiseDispatch (/Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:749:13)
W20141111-15:41:48.065(-6)? (STDERR)     at /Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:810:14
W20141111-15:41:48.065(-6)? (STDERR)     at flush (/Users/bcore/.meteor/packages/ecwyne:polymer-elements/.1.0.3.wcn5lx++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:108:17)
W20141111-15:41:48.065(-6)? (STDERR)     at process._tickCallback (node.js:419:13)
=> Exited with code: 8

**Comment by justindra** [comment]
@grigio Did you have a solution as to how to fix the issue?

**Comment by grigio** [comment]
Yes with an update or permissions fix it is gone

**Comment by ecwyne** [comment]
With the most recent updates, this should no longer be an issue. I have completely changed the way that components are stored and loaded. Also added some pretty sweet helper functions!
